# -*- coding: utf-8 -*-
"""day 2 data science

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1B45JAI3lR4CQ22TGYgpaY2dArZNYwsAu
"""

import numpy as np

list1=[1,2,3,4,5]
list2=[2,3,4,5,6]
list3=[4,5,6,7,8]

"""retriveing ([[3,4],[5,6]]) using indexing

"""

arr= np.array([list1,list2,list3])
arr

arr[1:3,1:3]

import pandas as pd
import seaborn as sns

sns.distplot(pd.DataFrame(arr.reshape(15,1)))